
# 本机执行
# 备份 playbook 目录到 /tmp/随机数/

# 删除 ./result.txt ./sorted_result
- hosts: localhost
  tasks:
    - name: On localhost remove `{{ playbook_dir }}/result.txt`.
      file:
        path: "{{ playbook_dir }}/result.txt"
        state: absent
    - name: On localhost remove `{{ playbook_dir }}/sorted_result.txt`.
      file:
        path: "{{ playbook_dir }}/sorted_result.txt"
        state: absent

# 异步收集, parse






# 集群执行
# 分发执行

- hosts: all
  tasks: 
    - name: Make /tmp/ansible/
      file:
        path: /tmp/ansible
        state: directory
    - name: Distribute serial_nslookup.sh
      copy:
        src: "{{ playbook_dir }}/serial_nslookup.sh"
        dest: /tmp/ansible/serial_nslookup.sh
        force: yes
    - name: Distribute domains.txt
      copy:
        src: "{{ playbook_dir }}/domains.txt"
        dest: /tmp/ansible/domains.txt
        force: yes
    # 循环覆盖收集
    - name: Collect serial_nslookup_host_result.txt
      fetch:
        src: /tmp/ansible/serial_nslookup_host_result.txt
        dest: /tmp/serial_nslookup_data/
      async: "{{ elapsed }}"
      poll: 0


    - name: Run Script /tmp/ansible/serial_nslookup.sh
      shell: bash /tmp/ansible/serial_nslookup.sh {{ elapsed }} {{ interval }}








# 本机执行
# 是否清理本机收集到的数据, 外部参数判断



## 常用命令
## ansible-playbook -i ./inventory.ini ./newplaybook.yaml --extra-vars "elapsed=120 interval=3"
##
## 删除集群主机的 /tmp/ansible 目录
## ansible all -i ./inventory.ini -m file -a "path=/tmp/ansible/ state=absent"
## 
## 
## 